In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [2]:
X = np.random.rand(10,10)  # 2D ndarray
X

array([[0.51204904, 0.86528549, 0.29509753, 0.63901415, 0.71218048,
        0.9172536 , 0.16748915, 0.44114978, 0.18208036, 0.47551205],
       [0.74523791, 0.23440465, 0.89572319, 0.44361647, 0.36120389,
        0.6477866 , 0.2859782 , 0.07141961, 0.44170963, 0.52829478],
       [0.52738982, 0.28759821, 0.96425963, 0.03125189, 0.06525591,
        0.38523602, 0.70403968, 0.33164519, 0.24370591, 0.07112078],
       [0.0441609 , 0.80820633, 0.37638078, 0.72840618, 0.79311647,
        0.01971454, 0.23428973, 0.39361616, 0.51828931, 0.51333917],
       [0.35777575, 0.38895631, 0.9558813 , 0.72021412, 0.2621144 ,
        0.94839766, 0.09531004, 0.28404689, 0.85486637, 0.47289376],
       [0.52333698, 0.76816629, 0.1872257 , 0.34388833, 0.60547391,
        0.50199418, 0.98033101, 0.81692952, 0.41064472, 0.76799245],
       [0.91421974, 0.51169497, 0.0229178 , 0.74057778, 0.25383662,
        0.45115983, 0.41082795, 0.00703045, 0.39519493, 0.2422539 ],
       [0.66231556, 0.29421608, 0.7378887

In [3]:
n_samples, n_features = X.shape
#n_components_ = n_components or n_features

In [4]:
 #Chuẩn hóa các tính năng bằng cách loại bỏ giá trị trung bình và chia tỷ lệ thành phương sai đơn vị
 X_std = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
 X_std

array([[ 0.21221805,  1.28609824, -0.56449042,  0.61820011,  0.7720817 ,
         1.34619441, -1.07631566,  0.19282547, -0.96448283, -0.03380108],
       [ 1.06421348, -1.01354064,  1.16857938, -0.16864634, -0.61920494,
         0.325326  , -0.68706228, -1.16293201,  0.02483891,  0.23203955],
       [ 0.26826825, -0.81964351,  1.36633722, -1.82919627, -1.79235574,
        -0.66933973,  0.68632913, -0.20871512, -0.7296576 , -2.07052093],
       [-1.49729124,  1.07803765, -0.32995242,  0.97817268,  1.09291553,
        -2.0541079 , -0.85686627,  0.0185252 ,  0.31664706,  0.15671551],
       [-0.35144576, -0.45018069,  1.34216204,  0.94518411, -1.01200004,
         1.46418285, -1.31343431, -0.38325253,  1.59917961, -0.04698812],
       [ 0.2534605 ,  0.93208673, -0.8757482 , -0.57024134,  0.34909217,
        -0.2270046 ,  1.59398544,  1.57076598, -0.09353448,  1.43927875],
       [ 1.68161748, -0.00278304, -1.3498489 ,  1.02718646, -1.04481352,
        -0.41958918, -0.27691309, -1.39903958

In [5]:
cov_mat = np.corrcoef(X, rowvar=False)
print('Covariance matrix: \n%s' % cov_mat)

Covariance matrix: 
[[ 1.         -0.21569781  0.11854232 -0.18210023 -0.55363457  0.14458279
  -0.15496594 -0.46972028 -0.40702784 -0.43442426]
 [-0.21569781  1.         -0.63758206  0.57707164  0.27805843 -0.29353845
   0.13089642  0.64579292 -0.45456962  0.10456072]
 [ 0.11854232 -0.63758206  1.         -0.48056954 -0.44491205  0.23006713
  -0.38827732 -0.40172766  0.17637864 -0.29326608]
 [-0.18210023  0.57707164 -0.48056954  1.          0.11618938  0.02204078
  -0.36771263  0.03687925  0.14393806  0.10210617]
 [-0.55363457  0.27805843 -0.44491205  0.11618938  1.         -0.03253671
   0.05459434  0.34284913  0.12686883  0.75116169]
 [ 0.14458279 -0.29353845  0.23006713  0.02204078 -0.03253671  1.
  -0.28580873 -0.16391511  0.33584701  0.24130684]
 [-0.15496594  0.13089642 -0.38827732 -0.36771263  0.05459434 -0.28580873
   1.          0.67603796 -0.24077776  0.1970957 ]
 [-0.46972028  0.64579292 -0.40172766  0.03687925  0.34284913 -0.16391511
   0.67603796  1.         -0.31948622  

In [6]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
eig_vals


array([ 3.39267637e+00,  2.25363455e+00,  1.66375776e+00,  9.42236508e-01,
        7.20301143e-01,  6.62263419e-01,  2.58154986e-01,  9.19112276e-02,
       -1.62799981e-16,  1.50640329e-02])

In [7]:
eig_vecs

array([[ 0.31559077, -0.3117023 ,  0.12057625,  0.54143568, -0.35356839,
         0.08655534, -0.41712682, -0.09426973,  0.21933845,  0.3634    ],
       [-0.40733887, -0.24909519,  0.34507089,  0.04048326,  0.21628435,
        -0.19222289, -0.1714724 , -0.57394448,  0.32548615, -0.32066956],
       [ 0.40802136,  0.1150748 , -0.21840137, -0.2150541 ,  0.39061609,
        -0.44051398, -0.39622753,  0.1931691 ,  0.42859043, -0.04117189],
       [-0.19629364,  0.08814964,  0.67080212, -0.04167116,  0.1850156 ,
         0.24774297, -0.13168336,  0.58610222,  0.19297783,  0.09100749],
       [-0.37192216,  0.31153429, -0.04845294,  0.00988748, -0.46974863,
        -0.44490612,  0.24908385,  0.0882831 ,  0.43932164,  0.28412926],
       [ 0.15164892,  0.34854416,  0.04978794,  0.71743107,  0.39942264,
        -0.07395517,  0.39534646, -0.02068147,  0.07190325, -0.10690628],
       [-0.26324772, -0.23541538, -0.52662824,  0.12066179,  0.05049816,
         0.48674464,  0.0586435 ,  0.22139595

In [8]:
idx = eig_vals.argsort()[::-1]
eig_vals, eig_vecs = eig_vals[idx], eig_vecs[:, idx]


In [9]:
# sắp xếp các giá trị riêng theo thứ tự giảm dần
k=5
print("Eigenvalues:\n", eig_vals[:k])
        # a matrix of eigenvectors (each column is an eigenvector)
print("Eigenvectors:\n", eig_vecs[:k])

Eigenvalues:
 [3.39267637 2.25363455 1.66375776 0.94223651 0.72030114]
Eigenvectors:
 [[ 0.31559077 -0.3117023   0.12057625  0.54143568 -0.35356839  0.08655534
  -0.41712682 -0.09426973  0.3634      0.21933845]
 [-0.40733887 -0.24909519  0.34507089  0.04048326  0.21628435 -0.19222289
  -0.1714724  -0.57394448 -0.32066956  0.32548615]
 [ 0.40802136  0.1150748  -0.21840137 -0.2150541   0.39061609 -0.44051398
  -0.39622753  0.1931691  -0.04117189  0.42859043]
 [-0.19629364  0.08814964  0.67080212 -0.04167116  0.1850156   0.24774297
  -0.13168336  0.58610222  0.09100749  0.19297783]
 [-0.37192216  0.31153429 -0.04845294  0.00988748 -0.46974863 -0.44490612
   0.24908385  0.0882831   0.28412926  0.43932164]]


In [10]:
explained_variance = (eig_vals / np.sum(eig_vals))[:k]
explained_variance_cumsum = np.cumsum(explained_variance)
total_var = np.sum(explained_variance)

In [11]:
print('Total variance explained:\n', total_var)
print('Explained variance:\n', explained_variance)
print('Explained variance cumsum:\n', explained_variance_cumsum)

Total variance explained:
 0.8972606333921741
Explained variance:
 [0.33926764 0.22536346 0.16637578 0.09422365 0.07203011]
Explained variance cumsum:
 [0.33926764 0.56463109 0.73100687 0.82523052 0.89726063]


In [12]:
# Projection matrix and dimensionality reduction
W = eig_vecs[:, 0:k]
#assert W.shape == (n_features, k)

In [13]:
PC_k = X.dot(W)
#assert PC_k.shape == (n_samples, k)

In [14]:
PC_k

array([[-0.69679894,  0.46628682,  0.46164624,  1.04633648,  0.41757818],
       [ 0.14104247,  0.59828848,  0.03256732,  0.76329399,  0.29902563],
       [ 0.13424369, -0.01023526, -0.47526354,  0.45547431,  0.58017057],
       [-0.95602865,  0.55756107,  0.3485374 ,  0.06961445,  0.22468088],
       [ 0.01206069,  1.01346289,  0.28725862,  0.64960389,  0.84501145],
       [-1.11832979,  0.28429303, -0.32879996,  0.95577429,  0.36452572],
       [-0.24078656,  0.128091  ,  0.53032949,  0.83973027,  0.00818389],
       [-0.21974707,  0.36986813, -0.27110416,  0.76652676,  0.150354  ],
       [-1.36199614,  0.09379403, -0.04986931,  0.71486656,  0.60151263],
       [-0.59141322,  1.25979714, -0.36043157,  0.64976084,  0.21953241]])

In [15]:
#@title Sử dụng SVD
U, s, Vt = np.linalg.svd(X, full_matrices=False)

In [16]:
V = Vt.T
S = np.diag(s)

In [17]:
eig_vals = (s ** 2) / (n_features - 1)

In [18]:
explained_variance = (eig_vals / np.sum(eig_vals))[:k]

In [19]:
explained_variance_cumsum = np.cumsum(explained_variance)

In [20]:
total_var = np.sum(explained_variance)

In [21]:
US_k = U[:, 0:k].dot(S[0:k, 0:k])


In [22]:
signs = np.sign(PC_k)*np.sign(US_k)

In [23]:
PC_k

array([[-0.69679894,  0.46628682,  0.46164624,  1.04633648,  0.41757818],
       [ 0.14104247,  0.59828848,  0.03256732,  0.76329399,  0.29902563],
       [ 0.13424369, -0.01023526, -0.47526354,  0.45547431,  0.58017057],
       [-0.95602865,  0.55756107,  0.3485374 ,  0.06961445,  0.22468088],
       [ 0.01206069,  1.01346289,  0.28725862,  0.64960389,  0.84501145],
       [-1.11832979,  0.28429303, -0.32879996,  0.95577429,  0.36452572],
       [-0.24078656,  0.128091  ,  0.53032949,  0.83973027,  0.00818389],
       [-0.21974707,  0.36986813, -0.27110416,  0.76652676,  0.150354  ],
       [-1.36199614,  0.09379403, -0.04986931,  0.71486656,  0.60151263],
       [-0.59141322,  1.25979714, -0.36043157,  0.64976084,  0.21953241]])